package com.example.collezioneeuro.model.repository

import com.example.collezioneeuro.R
import com.example.collezioneeuro.model.CECoin
import com.example.collezioneeuro.model.CECountry
import com.example.collezioneeuro.model.CECountryConstants

/**
 * FakeRepository crea dei valori di default.
 * Utilizzato per effettuare delle prove usando dati in locale.
 * Utilizza il realm repository.
 */
class CEFakeRepository : CERepositoryInterface {

    companion object {
        val SingleInstance = CEFakeRepository()

        val countries = getOriginalCountries()

        /**
         * Recupera le hardcoded countries del fake repository
         */
        fun getOriginalCountries() =
            arrayListOf(
                CECountry(
                    CECountryConstants.Countries.LUSSEMBURGO.itName,
                    CECountryConstants.Countries.LUSSEMBURGO.tag,
                    arrayListOf(
                        CECoin(
                            0.01,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/lu/Luxembourg_1cent.jpg"
                        ),
                        CECoin(
                            0.02,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/lu/Luxembourg_2cent.jpg"
                        ),
                        CECoin(
                            0.05,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/lu/Luxembourg_5cent.jpg"
                        ),
                        CECoin(
                            2.00,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/lu/Luxembourg_2euro.jpg"
                        ),
                        CECoin(
                            0.10,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/lu/Luxembourg_10cent.jpg"
                        ),
                        CECoin(
                            0.20,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/lu/Luxembourg_20cent.jpg"
                        ),
                        CECoin(
                            0.50,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/lu/Luxembourg_50cent.jpg"
                        ),
                        CECoin(
                            1.0,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/lu/Luxembourg_1Euro.jpg"
                        )
                    ),
                    R.drawable.flag_default,
                    "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Flag_of_Luxembourg.svg/800px-Flag_of_Luxembourg.svg.png"
                ),
                CECountry(
                    CECountryConstants.Countries.FINLANDIA.itName,
                    CECountryConstants.Countries.FINLANDIA.tag,
                    arrayListOf(
                        CECoin(
                            0.01,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/fi/Finland_1cent.jpg"
                        ),
                        CECoin(
                            0.02,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/fi/Finland_2cent.jpg"
                        ),
                        CECoin(
                            0.05,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/fi/Finland_5cent.jpg"
                        ),
                        CECoin(
                            1.00,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/fi/Finland_1euro.jpg"
                        ),
                        CECoin(
                            2.00,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/fi/Finland_2euro.jpg"
                        ),
                        CECoin(
                            0.10,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/fi/Finland_10cent.jpg"
                        ),
                        CECoin(
                            0.20,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/fi/Finland_20cent.jpg"
                        ),
                        CECoin(
                            0.50,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/fi/Finland_50cent.jpg"
                        )
                    ),
                    R.drawable.flag_default,
                    "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Finland.svg/800px-Flag_of_Finland.svg.png"
                ),
                CECountry(
                    CECountryConstants.Countries.SAN_MARINO.itName,
                    CECountryConstants.Countries.SAN_MARINO.tag,
                    arrayListOf(
                        CECoin(
                            0.01,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/sm/SanMarino_1cent.jpg"
                        ),
                        CECoin(
                            0.02,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/sm/SanMarino_2cent.jpg"
                        ),
                        CECoin(
                            0.05,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/sm/SanMarino_5cent.jpg"
                        ),
                        CECoin(
                            1.00,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/sm/SanMarino_1euro_2010.jpg"
                        ),
                        CECoin(
                            2.00,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/sm/SanMarino_2euro_2010.jpg"
                        ),
                        CECoin(
                            0.10,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/sm/SanMarino_10cent.jpg"
                        ),
                        CECoin(
                            0.20,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/sm/SanMarino_20cent.jpg"
                        ),
                        CECoin(
                            0.50,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/sm/SanMarino_50cent.jpg"
                        )
                    ),
                    R.drawable.flag_default,
                    "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Flag_of_San_Marino.svg/800px-Flag_of_San_Marino.svg.png"
                ),
                CECountry(
                    CECountryConstants.Countries.FRANCIA.itName,
                    CECountryConstants.Countries.FRANCIA.tag,
                    arrayListOf(
                        CECoin(
                            0.01,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/fr/France_1cent.jpg"
                        ),
                        CECoin(
                            0.02,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/fr/France_2cent.jpg"
                        ),
                        CECoin(
                            0.05,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/fr/France_5cent.jpg"
                        ),
                        CECoin(
                            2.00,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/fr/France_2euro.jpg"
                        ),
                        CECoin(
                            0.10,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/fr/France_10cent.jpg"
                        ),
                        CECoin(
                            0.20,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/fr/France_20cent.jpg"
                        ),
                        CECoin(
                            0.50,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/fr/France_50cent.jpg"
                        ),
                        CECoin(
                            1.0,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/fr/France_1Euro.jpg"
                        )
                    ),
                    R.drawable.flag_default,
                    "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Flag_of_France.svg/800px-Flag_of_France.svg.png"
                ),
                CECountry(
                    CECountryConstants.Countries.IRLANDA.itName,
                    CECountryConstants.Countries.IRLANDA.tag,
                    arrayListOf(
                        CECoin(
                            0.01,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/ie/Ireland_1cent.jpg"
                        ),
                        CECoin(
                            0.02,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/ie/Ireland_2cent.jpg"
                        ),
                        CECoin(
                            0.05,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/ie/Ireland_5cent.jpg"
                        ),
                        CECoin(
                            1.00,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/ie/Ireland_1euro.jpg"
                        ),
                        CECoin(
                            2.00,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/ie/Ireland_2euro.jpg"
                        ),
                        CECoin(
                            0.10,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/ie/Ireland_10cent.jpg"
                        ),
                        CECoin(
                            0.20,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/ie/Ireland_20cent.jpg"
                        ),
                        CECoin(
                            0.50,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/ie/Ireland_50cent.jpg"
                        )
                    ),
                    R.drawable.flag_default,
                    "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Flag_of_Ireland.svg/800px-Flag_of_Ireland.svg.png"
                ),
                CECountry(
                    CECountryConstants.Countries.ESTONIA.itName,
                    CECountryConstants.Countries.ESTONIA.tag,
                    arrayListOf(
                        CECoin(
                            0.01,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/et/Estonia_1cent.jpg"
                        ),
                        CECoin(
                            0.02,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/et/Estonia_2cent.jpg"
                        ),
                        CECoin(
                            0.05,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/et/Estonia_5cent.jpg"
                        ),
                        CECoin(
                            0.10,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/et/Estonia_10cent.jpg"
                        ),
                        CECoin(
                            0.20,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/et/Estonia_20cent.jpg"
                        ),
                        CECoin(
                            0.50,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/et/Estonia_50cent.jpg"
                        ),
                        CECoin(
                            1.0,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/et/Estonia_1Euro.jpg"
                        ),
                        CECoin(
                            2.0,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/et/Estonia_2Euro.jpg"
                        )
                    ),
                    R.drawable.flag_default,
                    "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Flag_of_Estonia.svg/800px-Flag_of_Estonia.svg.png"
                ),
                CECountry(
                    CECountryConstants.Countries.PORTOGALLO.itName,
                    CECountryConstants.Countries.PORTOGALLO.tag,
                    arrayListOf(
                        CECoin(
                            0.01,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/pt/Portugal_1cent.jpg"
                        ),
                        CECoin(
                            0.02,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/pt/Portugal_2cent.jpg"
                        ),
                        CECoin(
                            0.05,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/pt/Portugal_5cent.jpg"
                        ),
                        CECoin(
                            2.00,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/pt/Portugal_2euro.jpg"
                        ),
                        CECoin(
                            0.10,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/pt/Portugal_10cent.jpg"
                        ),
                        CECoin(
                            0.20,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/pt/Portugal_20cent.jpg"
                        ),
                        CECoin(
                            0.50,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/pt/Portugal_50cent.jpg"
                        ),
                        CECoin(
                            1.0,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/pt/Portugal_1Euro.jpg"
                        )
                    ),
                    R.drawable.flag_default,
                    "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Portugal.svg/600px-Flag_of_Portugal.svg.png"
                ),
                CECountry(
                    CECountryConstants.Countries.PAESI_BASSI.itName,
                    CECountryConstants.Countries.PAESI_BASSI.tag,
                    arrayListOf(
                        CECoin(
                            0.01,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/nl/Netherlands_1cent_2000.jpg"
                        ),
                        CECoin(
                            0.02,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/nl/Netherlands_2cent_2000.jpg"
                        ),
                        CECoin(
                            0.05,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/nl/Netherlands_5cent_2000.jpg"
                        ),
                        CECoin(
                            1.00,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/nl/Netherlands_1euro_2000.jpg"
                        ),
                        CECoin(
                            2.00,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/nl/Netherlands_2euro_2001.jpg"
                        ),
                        CECoin(
                            0.10,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/nl/Netherlands_10cent_2000.jpg"
                        ),
                        CECoin(
                            0.20,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/nl/Netherlands_20cent_2000.jpg"
                        ),
                        CECoin(
                            0.05,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/nl/Netherlands_50cents_2000.jpg"
                        )
                    ),
                    R.drawable.flag_default,
                    "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/800px-Flag_of_the_Netherlands.svg.png"
                ),
                CECountry(
                    CECountryConstants.Countries.SLOVENIA.itName,
                    CECountryConstants.Countries.SLOVENIA.tag,
                    arrayListOf(
                        CECoin(
                            0.01,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/sl/Slovenia_1cent.jpg"
                        ),
                        CECoin(
                            0.02,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/sl/Slovenia_2cent.jpg"
                        ),
                        CECoin(
                            0.05,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/sl/Slovenia_5cent.jpg"
                        ),
                        CECoin(
                            0.10,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/sl/Slovenia_10cent.jpg"
                        ),
                        CECoin(
                            0.20,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/sl/Slovenia_20cent.jpg"
                        ),
                        CECoin(
                            0.50,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/sl/Slovenia_50cent.jpg"
                        ),
                        CECoin(
                            1.0,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/sl/Slovenia_1Euro.jpg"
                        ),
                        CECoin(
                            2.0,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/sl/Slovenia_2Euro.jpg"
                        )
                    ),
                    R.drawable.flag_default,
                    "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Flag_of_Slovenia.svg/800px-Flag_of_Slovenia.svg.png"
                ),
                CECountry(
                    CECountryConstants.Countries.ANDORRA.itName,
                    CECountryConstants.Countries.ANDORRA.tag,
                    arrayListOf(
                        CECoin(
                            0.01,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/ad/Andorra_1cent.jpg"
                        ),
                        CECoin(
                            0.02,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/ad/Andorra_2cent.jpg"
                        ),
                        CECoin(
                            0.05,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/ad/Andorra_5cent.jpg"
                        ),
                        CECoin(
                            1.00,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/ad/Andorra_1euro.jpg"
                        ),
                        CECoin(
                            0.10,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/ad/Andorra_10cent.jpg"
                        ),
                        CECoin(
                            0.20,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/ad/Andorra_20cent.jpg"
                        ),
                        CECoin(
                            0.50,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/ad/Andorra_50cent.jpg"
                        ),
                        CECoin(
                            2.00,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/ad/ad_2euro.jpg"
                        )
                    ),
                    R.drawable.flag_default,
                    "https:////upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Andorra.svg/800px-Flag_of_Andorra.svg.png"
                ),
                CECountry(
                    CECountryConstants.Countries.LETTONIA.itName,
                    CECountryConstants.Countries.LETTONIA.tag,
                    arrayListOf(
                        CECoin(
                            0.01,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/lv/Latvia_1cent.jpg"
                        ),
                        CECoin(
                            0.02,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/lv/Latvia_2cent.jpg"
                        ),
                        CECoin(
                            0.05,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/lv/Latvia_5cent.jpg"
                        ),
                        CECoin(
                            1.00,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/lv/Latvia_1euro.jpg"
                        ),
                        CECoin(
                            2.00,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/lv/Latvia_2euro.jpg"
                        ),
                        CECoin(
                            0.10,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/lv/Latvia_10cent.jpg"
                        ),
                        CECoin(
                            0.20,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/lv/Latvia_20cent.jpg"
                        ),
                        CECoin(
                            0.50,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/lv/Latvia_50cent.jpg"
                        )
                    ),
                    R.drawable.flag_default,
                    "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Flag_of_Latvia.svg/800px-Flag_of_Latvia.svg.png"
                ),
                CECountry(
                    CECountryConstants.Countries.SPAGNA.itName,
                    CECountry.getTag(CECountryConstants.Countries.SPAGNA.tag),
                    arrayListOf(
                        CECoin(
                            0.01,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/es/Spain_1cent_1999.jpg"
                        ),
                        CECoin(
                            0.02,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/es/Spain_2cent_2002.jpg"
                        ),
                        CECoin(
                            0.05,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/es/Spain_5cent_1999.jpg"
                        ),
                        CECoin(
                            1.00,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/es/Spain_1euro_2014.jpg"
                        ),
                        CECoin(
                            2.00,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/es/Spain_2euro_2014.jpg"
                        ),
                        CECoin(
                            0.10,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/es/Spain_10cent_2003.jpg"
                        ),
                        CECoin(
                            0.20,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/es/Spain_20cent_2001.jpg"
                        ),
                        CECoin(
                            0.50,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/es/Spain_50cent_1999.jpg"
                        )
                    ),
                    R.drawable.flag_default,
                    "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Spain.svg/750px-Flag_of_Spain.svg.png"
                ),
                CECountry(
                    CECountryConstants.Countries.BELGIO.itName,
                    CECountryConstants.Countries.BELGIO.tag,
                    arrayListOf(
                        CECoin(
                            0.01,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/be/Belgium_1cent_2000.jpg"
                        ),
                        CECoin(
                            0.02,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/be/Belgium_2cent_2000.jpg"
                        ),
                        CECoin(
                            0.05,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/be/Belgium_5cent_1999.jpg"
                        ),
                        CECoin(
                            1.00,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/be/Belgium_1euro_2011.jpg"
                        ),
                        CECoin(
                            2.00,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/be/Belgium_2euroAl.jpg"
                        ),
                        CECoin(
                            0.10,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/be/Belgium_10cent_1999.jpg"
                        ),
                        CECoin(
                            0.20,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/be/Belgium_20cent_2002.jpg"
                        ),
                        CECoin(
                            0.50,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/be/Belgium_50cent_2002.jpg"
                        )
                    ),
                    R.drawable.flag_default,
                    "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_Belgium_%28civil%29.svg/800px-Flag_of_Belgium_%28civil%29.svg.png"
                ),
                CECountry(
                    CECountryConstants.Countries.ITALIA.itName,
                    CECountryConstants.Countries.ITALIA.tag,
                    arrayListOf(
                        CECoin(
                            0.01,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/it/Italy_1cent.jpg"
                        ),
                        CECoin(
                            0.02,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/it/Italy_2cent.jpg"
                        ),
                        CECoin(
                            0.05,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/it/Italy_5cent.jpg"
                        ),
                        CECoin(
                            1.00,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/it/Italy_1euro.jpg"
                        ),
                        CECoin(
                            2.00,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/it/Italy_2euro.jpg"
                        ),
                        CECoin(
                            0.10,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/it/Italy_10cent.jpg"
                        ),
                        CECoin(
                            0.20,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/it/Italy_20cent.jpg"
                        ),
                        CECoin(
                            0.50,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/it/Italy_50cent.jpg"
                        )
                    ),
                    R.drawable.flag_italia,
                    "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Flag_of_Italy.svg/800px-Flag_of_Italy.svg.png"
                ),
                CECountry(
                    CECountryConstants.Countries.LITUANIA.itName,
                    CECountryConstants.Countries.LITUANIA.tag,
                    arrayListOf(
                        CECoin(
                            0.01,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/lt/Lithuania_1cent_2015.jpg"
                        ),
                        CECoin(
                            0.02,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/lt/Lithuania_2cent_2015.jpg"
                        ),
                        CECoin(
                            0.05,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/lt/Lithuania_5cent_2015.jpg"
                        ),
                        CECoin(
                            1.00,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/lt/Lithuania_1euro_2015.jpg"
                        ),
                        CECoin(
                            2.00,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/lt/Lithuania_2euro_2015.jpg"
                        ),
                        CECoin(
                            0.10,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/lt/Lithuania_10cent_2015.jpg"
                        ),
                        CECoin(
                            0.20,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/lt/Lithuania_20cent_2015.jpg"
                        ),
                        CECoin(
                            0.50,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/lt/Lithuania_50cent_2014.jpg"
                        )
                    ),
                    R.drawable.flag_default,
                    "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Flag_of_Lithuania.svg/800px-Flag_of_Lithuania.svg.png"
                ),
                CECountry(
                    CECountryConstants.Countries.CIPRO.itName,
                    CECountryConstants.Countries.CIPRO.tag,
                    arrayListOf(
                        CECoin(
                            0.01,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/cy/Cyprus_1cent.jpg"
                        ),
                        CECoin(
                            0.02,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/cy/Cyprus_2cent.jpg"
                        ),
                        CECoin(
                            0.05,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/cy/Cyprus_5cent.jpg"
                        ),
                        CECoin(
                            1.00,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/cy/Cyprus_1euro.jpg"
                        ),
                        CECoin(
                            0.10,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/cy/Cyprus_10cent.jpg"
                        ),
                        CECoin(
                            0.20,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/cy/Cyprus_20cent.jpg"
                        ),
                        CECoin(
                            2.0,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/cy/Cyprus_2Euro.jpg"
                        ),
                        CECoin(
                            0.50,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/cy/Cyprus_50cent.jpg"
                        )
                    ),
                    R.drawable.flag_default,
                    "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_Cyprus.svg/800px-Flag_of_Cyprus.svg.png"
                ),
                CECountry(
                    CECountryConstants.Countries.AUSTRIA.itName,
                    CECountryConstants.Countries.AUSTRIA.tag,
                    arrayListOf(
                        CECoin(
                            0.01,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/at/Austria_1cent.jpg"
                        ),
                        CECoin(
                            0.02,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/at/Austria_2cent.jpg"
                        ),
                        CECoin(
                            0.05,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/at/Austria_5cent.jpg"
                        ),
                        CECoin(
                            0.10,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/at/Austria_10cent.jpg"
                        ),
                        CECoin(
                            0.20,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/at/Austria_20cent.jpg"
                        ),
                        CECoin(
                            0.50,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/at/Austria_50cent.jpg"
                        ),
                        CECoin(
                            1.0,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/at/Austria_1Euro.jpg"
                        ),
                        CECoin(
                            2.0,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/at/Austria_2Euro.jpg"
                        )
                    ),
                    R.drawable.flag_default,
                    "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Flag_of_Austria.svg/800px-Flag_of_Austria.svg.png"
                ),
                CECountry(
                    CECountryConstants.Countries.VATICANO.itName,
                    CECountryConstants.Countries.VATICANO.tag,
                    arrayListOf(
                        CECoin(
                            0.01,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/va/Vatican_1cent_2002.jpg"
                        ),
                        CECoin(
                            0.02,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/va/Vatican_2cent_2002.jpg"
                        ),
                        CECoin(
                            0.05,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/va/Vatican_5cent_2002.jpg"
                        ),
                        CECoin(
                            1.00,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/va/Vatican_1euro_2002.jpg"
                        ),
                        CECoin(
                            0.10,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/va/Vatican_10cent_2002.jpg"
                        ),
                        CECoin(
                            0.20,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/va/Vatican_20cent_2002.jpg"
                        ),
                        CECoin(
                            0.50,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/va/Vatican_50cent_2002.jpg"
                        ),
                        CECoin(
                            2.00,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/va/Vaticano_2euro_2002.jpg"
                        )
                    ),
                    R.drawable.flag_default,
                    "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_the_Vatican_City.svg/500px-Flag_of_the_Vatican_City.svg.png"
                ),
                CECountry(
                    CECountryConstants.Countries.GERMANIA.itName,
                    CECountryConstants.Countries.GERMANIA.tag,
                    arrayListOf(
                        CECoin(
                            0.01,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/de/Germany_1cent.jpg"
                        ),
                        CECoin(
                            0.02,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/de/Germany_2cent.jpg"
                        ),
                        CECoin(
                            0.05,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/de/Germany_5cent.jpg"
                        ),
                        CECoin(
                            1.00,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/de/Germany_1euro.jpg"
                        ),
                        CECoin(
                            2.00,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/de/Germany_2euro.jpg"
                        ),
                        CECoin(
                            0.10,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/de/Germany_10cent.jpg"
                        ),
                        CECoin(
                            0.20,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/de/Germany_20cent.jpg"
                        ),
                        CECoin(
                            0.50,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/de/Germany_50cent.jpg"
                        )
                    ),
                    R.drawable.flag_default,
                    "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Germany.svg/800px-Flag_of_Germany.svg.png"
                ),
                CECountry(
                    CECountryConstants.Countries.SLOVACCHIA.itName,
                    CECountryConstants.Countries.SLOVACCHIA.tag,
                    arrayListOf(
                        CECoin(
                            0.01,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/sk/Slovakia_1cent.jpg"
                        ),
                        CECoin(
                            0.02,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/sk/Slovakia_2cent.jpg"
                        ),
                        CECoin(
                            0.05,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/sk/Slovakia_5cent.jpg"
                        ),
                        CECoin(
                            0.10,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/sk/Slovakia_10cent.jpg"
                        ),
                        CECoin(
                            0.20,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/sk/Slovakia_20cent.jpg"
                        ),
                        CECoin(
                            0.50,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/sk/Slovakia_50cent.jpg"
                        ),
                        CECoin(
                            1.0,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/sk/Slovakia_1Euro.jpg"
                        ),
                        CECoin(
                            2.0,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/sk/Slovakia_2Euro.jpg"
                        )
                    ),
                    R.drawable.flag_default,
                    "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Flag_of_Slovakia.svg/512px-Flag_of_Slovakia.svg.png"
                ),
                CECountry(
                    CECountryConstants.Countries.MONACO.itName,
                    CECountryConstants.Countries.MONACO.tag,
                    arrayListOf(
                        CECoin(
                            0.01,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/mo/Monaco_1cent_2001.jpg"
                        ),
                        CECoin(
                            0.02,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/mo/Monaco_2cent_2001.jpg"
                        ),
                        CECoin(
                            0.05,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/mo/Monaco_5cent_2001.jpg"
                        ),
                        CECoin(
                            1.00,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/mo/Monaco_1euro_2006.jpg"
                        ),
                        CECoin(
                            2.00,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/mo/Monaco_2euro.jpg"
                        ),
                        CECoin(
                            0.10,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/mo/Monaco_10cent_2001.jpg"
                        ),
                        CECoin(
                            0.20,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/mo/Monaco_20cent_2001.jpg"
                        ),
                        CECoin(
                            0.50,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/mo/Monaco_50cent_2001.jpg"
                        )
                    ),
                    R.drawable.flag_default,
                    "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Flag_of_Monaco.svg/750px-Flag_of_Monaco.svg.png"
                ),
                CECountry(
                    CECountryConstants.Countries.MALTA.itName,
                    CECountryConstants.Countries.MALTA.tag,
                    arrayListOf(
                        CECoin(
                            0.01,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/mt/Malta_1cent.jpg"
                        ),
                        CECoin(
                            0.02,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/mt/Malta_2cent.jpg"
                        ),
                        CECoin(
                            0.05,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/mt/Malta_5cent.jpg"
                        ),
                        CECoin(
                            2.00,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/mt/Malta_2euro.jpg"
                        ),
                        CECoin(
                            0.10,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/mt/Malta_10cent.jpg"
                        ),
                        CECoin(
                            0.20,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/mt/Malta_20cent.jpg"
                        ),
                        CECoin(
                            0.50,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/mt/Malta_50cent.jpg"
                        ),
                        CECoin(
                            1.0,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/mt/Malta_1Euro.jpg"
                        )
                    ),
                    R.drawable.flag_default,
                    "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Malta.svg/800px-Flag_of_Malta.svg.png"
                ),
                CECountry(
                    CECountryConstants.Countries.GRECIA.itName,
                    CECountryConstants.Countries.GRECIA.tag,
                    arrayListOf(
                        CECoin(
                            0.01,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/gr/Greece_1cent.jpg"
                        ),
                        CECoin(
                            0.02,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/gr/Greece_2cent.jpg"
                        ),
                        CECoin(
                            0.05,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/gr/Greece_5cent.jpg"
                        ),
                        CECoin(
                            1.00,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/gr/Greece_1euro.jpg"
                        ),
                        CECoin(
                            2.00,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/gr/Greece_2euro.jpg"
                        ),
                        CECoin(
                            0.10,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/gr/Greece_10cent.jpg"
                        ),
                        CECoin(
                            0.20,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/gr/Greece_20cent.jpg"
                        ),
                        CECoin(
                            0.50,
                            null,
                            false,
                            "https://www.ecb.europa.eu/euro/coins/common/shared/img/gr/Greece_50cent.jpg"
                        )
                    ),
                    R.drawable.flag_default,
                    "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Greece.svg/600px-Flag_of_Greece.svg.png"
                )
            )

        /**
         * Crea le monete ad-hoc per l'Italia
         */
        private fun createItalianCoins(): ArrayList<CECoin> {
            val coins = CECountry.createCoins()
            coins[0].drawableId = R.drawable.italia_001
            coins[0].owned = true
            coins[1].drawableId = R.drawable.italia_002
            coins[1].owned = true
            coins[2].drawableId = R.drawable.italia_005
            coins[3].drawableId = R.drawable.italia_010
            coins[3].owned = true
            coins[4].drawableId = R.drawable.italia_020
            coins[5].drawableId = R.drawable.italia_050
            coins[6].drawableId = R.drawable.italia_100
            coins[6].owned = true
            coins[7].drawableId = R.drawable.italia_200
            return coins
        }

    }

    override suspend fun saveCountries(ceCountries: ArrayList<CECountry>) {
        for (ceCountry in ceCountries) {
            saveCountry(ceCountry)
        }
    }

    override suspend fun saveCountry(ceCountry: CECountry) {
        CERealmRepository().saveCountry(ceCountry)
    }

    override suspend fun editCountry(oldCountry: CECountry, newCountry: CECountry) {
        CERealmRepository().editCountry(oldCountry, newCountry)
    }

    override suspend fun getCountries(): ArrayList<CECountry> {
        return CERealmRepository().getCountries()
    }

    override suspend fun setOwned(ceCountry: CECountry, ceCoin: CECoin, owned: Boolean) {
        CERealmRepository().setOwned(ceCountry, ceCoin, owned)
    }

    override suspend fun clearAndSet(ceCountries: ArrayList<CECountry>) {
        clear()
        countries.addAll(ceCountries)
        saveCountries(countries)
    }

    override suspend fun clear() {
        CERealmRepository().clear()
        countries.clear()
    }

}